### ISSUE TITLE
Middleware do not answer properly on rest api login if bruteForce attack detected

### ISSUE THREAD

**Issue by stan-golembivsky** [cuba-platform/restapi#103]
### Environment

- Platform version: 7.2.4 
- Addon version: 7.2.0 

### Description of the bug or enhancement
- set cuba.bruteForceProtection.enabled = true
- try to login with the same login and wrong password via rest api more than 5 times (cuba.bruteForceProtection.maxLoginAttemptsNumber = 5)

BTW: If you are trying to login via cuba app you will see the appropriate message

Rest login eventually throws `LoginException` not `AccountLockedException`

P.S. Method `AuthenticationManagerBean:authenticateInternal` throws `LoginException` but inside it method `provider.authenticate(credentials)` throws proper `AccountLockedException`

**Comment by gorbunkov** [comment]
Fixed in [commit](https://github.com/cuba-platform/cuba/commit/70c0b2dd7a1558f75445f7f452bf1e68f2a1fbbf).

When the maximum login attempts number is exceeded the token response should contain the following text:
```
{
    "error": "invalid_grant",
    "error_description": "User temporarily blocked"
}
```
