### ISSUE TITLE
metadataTools.getAllEnums() method returns only enums used in entities

### ISSUE THREAD

**Issue by natfirst** [cuba-platform/restapi#118]
### Environment

- Platform version: 7.2
- Addon version: 7.2.1
- Forum issue: https://www.cuba-platform.ru/discuss/t/oshibka-pri-rabote-rest-metoda-rest-v2-metadata-enums/4725

### Description of the bug or enhancement

1. Create several enums in the project
2. Create an entity with enum attribute - use one of the created enums as a type
3. Try to get all enums using rest/v2/metadata/enums method

*A.R* List will contain only enums used in entities
*E.R.* List should contain all enums

**Comment by knstvk** [comment]
The javadoc reads:
```
Returns:
collection of all Java enums used as a type of an entity attribute
```
