### ISSUE TITLE
Nulls are always first when sorting by association attribute by instance name 

### ISSUE THREAD

**Issue by IskandarovRost** [cuba-platform/restapi#121]
### Environment

- Platform version: 7.2.8(7.2.9)

### Description of the bug or enhancement
See "When sorting by an Association field use the instance name rather than the id" #108

- Minimal reproducible example
1) there is an entity with a link to another entity.
The another entity has instance name defined
```
@Table(name = "LIBRARY_NEW_ENTITY")
@Entity(name = "library_NewEntity")
public class NewEntity extends StandardEntity {
    private static final long serialVersionUID = -491449145451121237L;

    @Column(name = "NEW_FLD")
    private String newFld;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "BOOK_ID")
    private Book book;
```
2) Create a view which includes the link attribute
```
 <view entity="library_NewEntity" name="newEntity-view" extends="_local">
        <property name="book" view="_local">
            <property name="literatureType" view="_minimal"/>
            <property name="authors" view="_minimal"/>
        </property>
    </view>
```

3) Create frontend module and frontend management for the entity with the link
4) then create several instances of both the entities
5) leave the link empty in several instances
6) Check sorting in the table 

- Expected behavior
- Actual behavior
The string with empty link is always on top (not regarding ascending or descending):
![image.png](https://images.zenhubusercontent.com/5aec53f14b5806bc2bd1c28a/e35d6c56-e2b9-4a4f-9afe-54a12c2e69d0)
![image.png](https://images.zenhubusercontent.com/5aec53f14b5806bc2bd1c28a/d1dba11a-ca8e-4119-a394-7c0657d252b9)

**Comment by plakhov** [comment]
Actual behavior reproduces only in React UI.
Project for reproduce
[https://app.zenhub.com/files/176701911/b45cb6c0-7c84-4586-98ec-3add254b4150/download](https://app.zenhub.com/files/176701911/b45cb6c0-7c84-4586-98ec-3add254b4150/download)
