### ISSUE TITLE
Support for Java 8 Date/Time API in parameters

### ISSUE THREAD

**Issue by dtaimanov** [cuba-platform/restapi#125]
### Environment:
- Platform version: 7.2
- Addon version: 7.2

### Description:
Detais: https://www.cuba-platform.com/discuss/t/rest-api-support-for-java-8-time-module-java-time/13874

Technical description: `RestParseUtils#toObject(Type,String,String)` doesn't support LocalDate and other Java 8 Date/Time API types.
Support could be implemented either on `RestParseUtils` or on `EntitySerializationAPI` level.

**Comment by knstvk** [comment]
The same problem with query parameters: https://www.cuba-platform.com/discuss/t/rest-query-on-localdate-possible-bug/14672

**Comment by lovtsovaik** [comment]
Need to support also java.sql.Time

**Comment by lovtsovaik** [comment]
Examples of values:

- java.time.LocalDate: "2010-10-10",
- java.time.LocalDateTime: "2010-10-10 15:15:15.001",
- java.time.LocalTime: "15:15:15",
- java.time.OffsetDateTime: "2010-10-10 15:15:15.001 +0300",
- java.time.OffsetTime: "15:15:15 +0300"

Examples of values for not java.time.*:

- java.sql.Time: "15:15:15",
- java.util.Date: "2010-10-10"
