### ISSUE TITLE
Building from source and running locally

### ISSUE THREAD

**Issue by bartekspitza** [cuba-platform/restapi#126]
I would like to address and help on #125 but I'm wondering how I would go about building this addon and running it locally. I have managed to build [cuba](https://github.com/cuba-platform/cuba) itself from source and run it, but not sure how I would integrate this addon. 

Any guidance in the right direction would be awesome!

**Comment by knstvk** [comment]
- Clone the Git repo
- Open the project in the IDE, import as Gradle project
- See instructions in `test/restapi-demo/README.md` for testing
- Publish the add-on to the local Maven repo (.m2): `./gradlew install`
- Use in an application by defining `mavenLocal()` in the repositories list

Hope this helps. If something goes wrong, write us on the support forum please.
