### ISSUE TITLE
Incorrect response when submitting 'null' to enum property marked as 'required' 

### ISSUE THREAD

**Issue by vadimbasko** [cuba-platform/restapi#127]
* checkout sample project https://github.com/cuba-platform/frontend/tree/master/sample-car-rent
* try to submit car with undefined carType, which is mandatory
```{"manufacturer":"Tesla"}```

AR: 
{"error":"Server error","details":""}

ER:
JSON response with validation error for carType property

**Comment by plakhov** [comment]
After discussion with @andreysubbotin and @knstvk have been made a decision. If needed get a detailed message about an error must use bean validation annotation, e.g. NotNull because Column annotation sets the constraint only on the database level.
