### ISSUE TITLE
Incorrect property path in validation response when submitting entity with invalid data in composition property

### ISSUE THREAD

**Issue by vadimbasko** [cuba-platform/restapi#128]
* checkout sample project https://github.com/cuba-platform/frontend/tree/master/sample-car-rent
* add `nullable=false` to `quantity` property of `CompositionO2OTestEntity` class
```
    @Column(name = "QUANTITY", nullable = false)
    @NotNull
    private Integer quantity;
```
* restart app, apply update scripts
* try to submit `DatatypesTestEntity` which contains `compositionO2Oattr` with empty `quantity`

```{"compositionO2Oattr":{"quantity":null,"name":"Lorem","nestedComposition":null}}```

AR
No mention of `compositionO2Oattr` in validation response
```
[{"message":"should be set","messageTemplate":"{javax.validation.constraints.NotNull.message}","path":"quantity","invalidValue":null}]
```

ER
Validation response should contains error with path `compositionO2Oattr.quantity`

**Comment by plakhov** [comment]
For the right work "NotNull" annotation in "CompositionO2Oattr" entity needed to add "Valid" annotation over "compositionO2Oattr" field in "DatatypesTestEntity".
For example:
_Before_
```
    @Composition
    @OnDelete(DeletePolicy.CASCADE)
    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "COMPOSITION_O2_OATTR_ID")
    protected CompositionO2OTestEntity compositionO2Oattr;
```

_After_
```
    @Valid
    @Composition
    @OnDelete(DeletePolicy.CASCADE)
    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "COMPOSITION_O2_OATTR_ID")
    protected CompositionO2OTestEntity compositionO2Oattr;
```
So we saw a full path in the error message
```
    {
        "message": "may not be null",
        "messageTemplate": "{javax.validation.constraints.NotNull.message}",
        "path": "compositionO2Oattr.quantity",
        "invalidValue": null
    }
```
