### ISSUE TITLE
No useful message from backend in case invoke CustomException/SystemException

### ISSUE THREAD

**Issue by maistrenkoIulia** [cuba-platform/restapi#130]
https://www.cuba-platform.com/discuss/t/rest-api-exception-handling/14171

Environment
CUBA Platform version: 7.2.10
CUBA Studio plugin version: 15.0.SNAPSHOT2676-202
IntelliJ version: IntelliJ IDEA 2020.2.4 (Community Edition)

Description of the bug or enhancement
TC:
open attached project ([restex.zip](https://github.com/cuba-platform/restapi/files/5608024/restex.zip))
run app
open 
http://localhost:8080/app/rest/v2/services/restex_ExceptionTestService/methodThrowsCustomException
http://localhost:8080/app/rest/v2/services/restex_ExceptionTestService/methodThrowsSysException
AR:
responce with no details value
```
{
    "error": "Server error",
    "details": ""
}
```

**Comment by plakhov** [comment]
If you want to see the useful detailed message for the custom exception you need to create a handler for the exception. 
For system exception, we don't provide a detailed message about the server error

**Comment by plakhov** [comment]
You can create an exception handler through the Spring mechanisms. The class should declare in 'web' module
Hadler example:

```
@ControllerAdvice("com.haulmont.addon.restapi.api.controllers")
@Order(Ordered.HIGHEST_PRECEDENCE)
public class CustomRestControllerExceptionHandler {

    private Logger log = LoggerFactory.getLogger(CustomRestControllerExceptionHandler.class);

    @ExceptionHandler(CustomHttpClientErrorException.class)
    @ResponseBody
    public ResponseEntity<ErrorInfo> handleException(Exception e) {
        log.error("Exception in REST controller", e);
        CustomHttpClientErrorException ex = (CustomHttpClientErrorException) e;
        ErrorInfo errorInfo = new ErrorInfo(ex.getStatusCode().getReasonPhrase(), ex.getStatusText());
        return new ResponseEntity<>(errorInfo, ex.getStatusCode());
    }
}
```
Use the current handler you can get the useful message
