### ISSUE TITLE
Add-on should depend on Spring Security 5.5

### ISSUE THREAD

**Issue by gorbunkov** [cuba-platform/restapi#146]
In CUBA issue https://github.com/cuba-platform/cuba/issues/3282 Spring Security dependency has been upgraded to version `5.5`. REST API add-on takes Spring Security version from CUBA BOM file. In order to actually update Spring Security dependency in REST API we need to build the new add-on release.

This should also fix SAML add-on issue https://github.com/cuba-platform/saml-addon/issues/30, because that issue is only relevant to specific Spring Security 5.2 versions. After REST API add-on depends on Spring Security 5.5, the SAML issue should disappear.

**Comment by gorbunkov** [comment]
For QA: please do a smoke-testing of the restapi add-on

**Comment by igisho** [comment]
@gorbunkov done: https://github.com/cuba-platform/cuba/issues/3298
