### ISSUE TITLE
RefreshToken and AccessToken entity classes are not enhanced

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/restapi#16]
### Environment

- Platform version: 7.1
- Addon version: 0.1-SNAPSHOT
- Client type: Web

### Description of the bug or enhancement

- Minimal reproducible example

Run application on 7.1-SNAPSHOT with REST-API.

- Actual behavior

```
2019-04-19 11:27:38.381 ERROR [main] com.haulmont.cuba.core.sys.persistence.EclipseLinkSessionEventListener - 
=================================================================
Problems with entity enhancement detected:
Entity class RefreshToken is missing some of enhancing interfaces: CubaEnhanced; PersistenceObject; PersistenceWeaved; PersistenceWeavedFetchGroups; PersistenceWeavedChangeTracking;
Entity class AccessToken is missing some of enhancing interfaces: CubaEnhanced; PersistenceObject; PersistenceWeaved; PersistenceWeavedFetchGroups; PersistenceWeavedChangeTracking;
```

Also, there is no entitiesEnhancing in build.gradle of the addon: https://github.com/cuba-platform/restapi/blob/master/build.gradle#L128

**Comment by dtsaryov** [comment]
@NikitaShchienko 

Add `entitiesEnhancing` configuration for `global` module.
