### ISSUE TITLE
"responseView" method parameter for entity create and update operations

### ISSUE THREAD

**Issue by gorbunkov** [cuba-platform/restapi#28]
By default, entity create and update operation must return a result that contains just the following fields:
```json
{
   "id": "<entityId>",
   "_entityName": "<entityName>",
   "_instanceName": "<intanceName>"
}
```

If other entity fields are required in the response, then an optional "responseView" query parameter must be passed in the request URL. In the case the creates/updated entity must be reloaded with this view and returned in the response JSON.

#### Breaking changes
Added optional parameter "responseView" for create/update request. Now, by default, only 3 parameters are passed in the response.
```json
{
   "id": "<entityId>",
   "_entityName": "<entityName>",
   "_instanceName": "<intanceName>"
}
```
To disable this function, you must set the config `cuba.rest.responseViewEnabled` to `false`.

**Comment by dtsaryov** [comment]
@NikitaShchienko Introduce new configuration that will disable this feature to avoid errors in migrated projects

**Comment by NikitaShchienko** [comment]
Ticket for changing the config when migrating version to 7.2: [Youtrack](https://youtrack.haulmont.com/issue/STUDIO-6636)
