### ISSUE TITLE
Ability to sort entities by multiple attributes

### ISSUE THREAD

**Issue by web-devel** [cuba-platform/restapi#33]
Currently in entities load/search methods it's possible to specify the only attribute for sorting.

**Comment by gorbunkov** [comment]
When you get a list of entities there is a *sort* request parameter (see [swagger documentation](http://files.cuba-platform.com/swagger/7.0/#!/Entities/get_entities_entityName)). The parameter should accept a comma-separated list of attributes with attribute names and ordering, e.g. `sort=+age,-lastname`
