### ISSUE TITLE
Introduce isNull entity search condition

### ISSUE THREAD

**Issue by web-devel** [cuba-platform/restapi#34]
### Description
Introduce `isNull` entity search condition for Rest API Add-on.

### Updates
Created a platform-independent enum `RestFilterOp` for the Rest API Add-on and added a new condition `isNull`.

Example:
```
  "filter": {
    "conditions": [
      {
        "property": "name",
        "operator": "isNull"
      }
    ]
  }
}
```

**Comment by gorbunkov** [comment]
The issue is about this endpoint: http://files.cuba-platform.com/swagger/7.0/#!/Entities/get_entities_entityName_search
