### ISSUE TITLE
Provide method to obtain entity search count

### ISSUE THREAD

**Issue by web-devel** [cuba-platform/restapi#35]
## Description
Currently it's possible to obtain search result count by using `returnCount` parameter. However there are some cases when only count is needed.
## Updates

Added a new endpoint `/entities/{entityName}/search/count` for GET and POST methods.

**Comment by gorbunkov** [comment]
The issue is about the `/entities/{entityName}/search` endpoint (see [swagger docs](http://files.cuba-platform.com/swagger/7.0/#!/Entities/get_entities_entityName_search)).
We need to add new endpoints  `/entities/{entityName}/search/count` for GET and POST methods
