### ISSUE TITLE
Permission config is not registered in app-component.xml

### ISSUE THREAD

**Issue by web-devel** [cuba-platform/restapi#39]
It's not possible to setup REST API permissions from Generic UI.

STR:
* Open Role editor 
* Open *Specific* tab

AR: 
REST API permissions are not present.

ER:
Use REST API permission should be available

**Comment by natfirst** [comment]
REST API permissions are not present in the project without REST API
![image](https://user-images.githubusercontent.com/17950251/64850383-597d5c80-d626-11e9-914b-62b861024634.png)

Permissions will be presented in the roles setting after adding REST API add-on to the project
![image](https://user-images.githubusercontent.com/17950251/64850901-62226280-d627-11e9-9e35-fb07110d8166.png)
