### ISSUE TITLE
Ability to set max results and offset for predefined rest queries

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/restapi#58]
@haulmont-git commented on [Thu Aug 03 2017](https://github.com/cuba-platform/fts/issues/11)

Typical usage: implement /recent query that returns 10 last orders / payments / etc
We want to set limit on server as business requirement

---
Original issue: https://youtrack.haulmont.com/issue/PL-9483

**Comment by gorbunkov** [comment]
We can add `maxResults` attribute to the [query config]9https://doc.cuba-platform.com/manual-latest/rest_api_v2_queries_config.html):
```xml
<query name="recent" entity="sample$Order" view="orderBrowse" maxResults="10">
    <jpql><![CDATA[select o from sample$Order o order by o.date desc]]></jpql>
</query>
```

**Comment by natfirst** [comment]
Two attributes were added:
- `limit` allows you to set the number of objects returned on one page
- `offset` allows you to specify the ranking number of the first item on the page
