### ISSUE TITLE
'id' attribute of 'CategoryAttributeConfiguration' entity can't be serialized

### ISSUE THREAD

**Issue by NikitaShchienko** [cuba-platform/restapi#82]
### Environment

- Platform version: 7.2-SNAPSHOT 
- Add-on version: 7.2-SNAPSHOT

### Description of the bug

'id' attribute of 'CategoryAttributeConfiguration' entity can't be serialized.

Minimal reproducible example

1. Run an application with the Rest Add-on
2. Send Rest-request: `http://localhost:8080/app/rest/v2/entities/sys$CategoryAttribute`

**Expected behavior**: Get JSON-object CategoryAttributes
**Actual behavior**:
```
{
     'error':'Server error',
     'details':''
}
```
Exception:
```
18:29:11.277 ERROR c.h.a.r.a.c.RestControllerExceptionHandler- Exception in REST controller
com.haulmont.cuba.core.app.serialization.EntitySerializationException: Primary key property not found for entity sys$CategoryAttributeConfiguration
```

**Comment by knstvk** [comment]
Looks like we should add @Id annotation to the entity. Requires testing.
